apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: portales
  title: Portales
  description: Portales
  annotations:
    backstage.io/techdocs-ref: dir:.
    github.com/project-slug: robercalvo/backstage2-docs
spec:
  type: documentation
  lifecycle: experimental
  owner: team-docs
