apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: normativa-regulacion
  title: Normativas y Regulación
  description: Normativas y Regulación
  annotations:
    backstage.io/techdocs-ref: dir:.
    github.com/project-slug: robercalvo/backstage2-docs
spec:
  type: documentation
  lifecycle: experimental
  owner: team-docs
